platform:ios,’8.0’

use_frameworks!

flutter_application_path = '../../flutter_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

def all_pods
    pod "AFNetworking"
    pod "SSZipArchive"
    pod "SVProgressHUD"
    pod "HJMacros", "0.6.0"
    pod "Masonry", "1.1.0"
    pod "MaterialControls", "~> 1.2.2"
end

target :FlutterPrograms do
    all_pods
    
    # 替换 Flutter 官方 Flutter.framework
    FileUtils.rm_r('../../flutter_module/.ios/Flutter/engine/Flutter.framework', :force => true)
    FileUtils.cp_r('../flutter_frameworks/ios_debug_all/Flutter.framework', '../../flutter_module/.ios/Flutter/engine/Flutter.framework')
end

target :FlutterProgramsRelease do
    all_pods
    
    # 替换 Flutter 官方 Flutter.framework
    FileUtils.rm_r('../../flutter_module/.ios/Flutter/engine/Flutter.framework', :force => true)
    FileUtils.cp_r('../flutter_frameworks/ios_debug_all/Flutter.framework', '../../flutter_module/.ios/Flutter/engine/Flutter.framework')
end

